<?php
class RSfilesReportsController extends JControllerLegacy{
	public function display($cachable = false, $urlparams = [])
	{
		return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
	}
}
